framework:
    cache:
        # Configure the application cache
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: 'csgo_stats_app'

when@test:
    framework:
        cache:
            app: cache.adapter.array

when@dev:
    framework:
        cache:
            app: cache.adapter.filesystem

when@prod:
    framework:
        cache:
            app: cache.adapter.redis
            default_redis_provider: '%env(REDIS_URL)%'
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system